version: "3.7"
services:
  item-app:
    image:
    restart: always
    port:
      - 80:8080
    depends_on:
      - item-db
  item-db:
    image: mongo:3
    restart: always
    volumes:
      - app-db:/data/db

volumes:
  app-db:
